language: android
android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-27.0.0

    # The SDK version used to compile your project
    - android-27
    - extra-android-m2repository
    - extra-android-support
  before_install:
    - chmod +x gradlew

  script:  
    - ./gradlew assembleRelease

  licenses:
    - android-sdk-license-.+
    - '.+'

